/**
 * Reconstructed Kenneth Fire spread stages.
 *
 * HONESTY NOTE: these polygons are a labelled historical RECONSTRUCTION built
 * from official incident facts (start point/time, spread direction, final
 * 1,052-acre size) and the real geography of Upper Las Virgenes Canyon — they
 * are NOT surveyed perimeters. Stage areas are believable interval estimates;
 * the final ring matches the official acreage. The eastern (West Hills) and
 * southern (Hidden Hills) edges stay nearly fixed across later stages,
 * reflecting structure-defense lines, while growth runs west toward
 * Las Virgenes Canyon with the Santa Ana wind.
 *
 * Generated by a one-off script that tunes stage areas and verifies that each
 * stage ring nests strictly inside the next.
 */
import type { LatLng } from '../lib/interpolatePolygon';

export interface SpreadStage {
  id: string;
  name: string;
  /** Short label shown on the timeline, e.g. "3:45 PM". */
  timeLabel: string;
  /** Stage time used by the animation clock. */
  timeIso: string;
  description: string;
  /**
   * Accent colors for UI chips/legends. On the map itself, reached stages
   * render as subtle charcoal burned-history fills (see spreadModelConfig).
   */
  fillColor: string;
  strokeColor: string;
  /** Open ring (no repeated end vertex), counter-clockwise. */
  ring: LatLng[];
}

export const SPREAD_STAGES: SpreadStage[] = [
  {
    id: 'ignition',
    name: 'Ignition',
    timeLabel: '3:34 PM',
    timeIso: '2025-01-09T15:34:00-08:00',
    description: 'Reported start near the Victory Blvd trailhead on the West Hills edge.',
    fillColor: 'rgba(255, 216, 70, 0.55)',
    strokeColor: 'rgba(255, 232, 150, 0.95)',
    ring: [
      { lat: 34.18480, lng: -118.66898 },
      { lat: 34.18536, lng: -118.66933 },
      { lat: 34.18571, lng: -118.67024 },
      { lat: 34.18571, lng: -118.67136 },
      { lat: 34.18536, lng: -118.67227 },
      { lat: 34.18480, lng: -118.67262 },
      { lat: 34.18424, lng: -118.67227 },
      { lat: 34.18389, lng: -118.67136 },
      { lat: 34.18389, lng: -118.67024 },
      { lat: 34.18424, lng: -118.66933 },
    ],
  },
  {
    id: 'early',
    name: 'Early spread',
    timeLabel: '3:45 PM',
    timeIso: '2025-01-09T15:45:00-08:00',
    description: 'Wind-driven push west into Upper Las Virgenes Canyon open space.',
    fillColor: 'rgba(255, 173, 51, 0.46)',
    strokeColor: 'rgba(255, 196, 110, 0.92)',
    ring: [
      { lat: 34.18761, lng: -118.66622 },
      { lat: 34.18620, lng: -118.66580 },
      { lat: 34.18466, lng: -118.66608 },
      { lat: 34.18340, lng: -118.66692 },
      { lat: 34.18255, lng: -118.66833 },
      { lat: 34.18227, lng: -118.67001 },
      { lat: 34.18255, lng: -118.67170 },
      { lat: 34.18354, lng: -118.67275 },
      { lat: 34.18480, lng: -118.67296 },
      { lat: 34.18592, lng: -118.67212 },
      { lat: 34.18677, lng: -118.67057 },
      { lat: 34.18733, lng: -118.66875 },
    ],
  },
  {
    id: 'broader',
    name: 'Broader spread',
    timeLabel: '5:00 PM',
    timeIso: '2025-01-09T17:00:00-08:00',
    description: 'Run across the open hills toward Lasky Mesa; south edge nears Hidden Hills.',
    fillColor: 'rgba(255, 126, 28, 0.42)',
    strokeColor: 'rgba(255, 158, 80, 0.92)',
    ring: [
      { lat: 34.19110, lng: -118.66758 },
      { lat: 34.19000, lng: -118.66588 },
      { lat: 34.18813, lng: -118.66529 },
      { lat: 34.18609, lng: -118.66520 },
      { lat: 34.18405, lng: -118.66571 },
      { lat: 34.18201, lng: -118.66656 },
      { lat: 34.18014, lng: -118.66843 },
      { lat: 34.17835, lng: -118.67115 },
      { lat: 34.17691, lng: -118.67438 },
      { lat: 34.17597, lng: -118.67778 },
      { lat: 34.17555, lng: -118.68135 },
      { lat: 34.17606, lng: -118.68441 },
      { lat: 34.17742, lng: -118.68645 },
      { lat: 34.17963, lng: -118.68696 },
      { lat: 34.18201, lng: -118.68628 },
      { lat: 34.18439, lng: -118.68475 },
      { lat: 34.18660, lng: -118.68246 },
      { lat: 34.18855, lng: -118.67948 },
      { lat: 34.19000, lng: -118.67591 },
      { lat: 34.19085, lng: -118.67183 },
    ],
  },
  {
    id: 'major',
    name: 'Major spread',
    timeLabel: '5:30 PM',
    timeIso: '2025-01-09T17:30:00-08:00',
    description: 'Continued spread west and south; structure defense along neighborhood edges.',
    fillColor: 'rgba(235, 78, 22, 0.40)',
    strokeColor: 'rgba(255, 120, 70, 0.92)',
    ring: [
      { lat: 34.19117, lng: -118.66726 },
      { lat: 34.18988, lng: -118.66565 },
      { lat: 34.18802, lng: -118.66508 },
      { lat: 34.18600, lng: -118.66500 },
      { lat: 34.18398, lng: -118.66548 },
      { lat: 34.18188, lng: -118.66629 },
      { lat: 34.17994, lng: -118.66791 },
      { lat: 34.17808, lng: -118.67033 },
      { lat: 34.17646, lng: -118.67341 },
      { lat: 34.17525, lng: -118.67680 },
      { lat: 34.17444, lng: -118.68036 },
      { lat: 34.17420, lng: -118.68408 },
      { lat: 34.17485, lng: -118.68747 },
      { lat: 34.17630, lng: -118.69022 },
      { lat: 34.17848, lng: -118.69208 },
      { lat: 34.18091, lng: -118.69248 },
      { lat: 34.18333, lng: -118.69151 },
      { lat: 34.18552, lng: -118.68941 },
      { lat: 34.18762, lng: -118.68650 },
      { lat: 34.18940, lng: -118.68278 },
      { lat: 34.19069, lng: -118.67834 },
      { lat: 34.19150, lng: -118.67308 },
    ],
  },
  {
    id: 'final',
    name: 'Final footprint',
    timeLabel: 'Evening',
    timeIso: '2025-01-09T19:00:00-08:00',
    description: 'Forward progress slows toward Las Virgenes Canyon. Official size: 1,052 acres.',
    fillColor: 'rgba(158, 30, 32, 0.38)',
    strokeColor: 'rgba(205, 75, 70, 0.92)',
    ring: [
      { lat: 34.19149, lng: -118.66700 },
      { lat: 34.19007, lng: -118.66543 },
      { lat: 34.18810, lng: -118.66488 },
      { lat: 34.18598, lng: -118.66480 },
      { lat: 34.18385, lng: -118.66527 },
      { lat: 34.18173, lng: -118.66606 },
      { lat: 34.17984, lng: -118.66763 },
      { lat: 34.17795, lng: -118.66999 },
      { lat: 34.17630, lng: -118.67299 },
      { lat: 34.17504, lng: -118.67629 },
      { lat: 34.17425, lng: -118.67991 },
      { lat: 34.17402, lng: -118.68369 },
      { lat: 34.17465, lng: -118.68715 },
      { lat: 34.17590, lng: -118.69014 },
      { lat: 34.17764, lng: -118.69266 },
      { lat: 34.17968, lng: -118.69487 },
      { lat: 34.18181, lng: -118.69605 },
      { lat: 34.18401, lng: -118.69550 },
      { lat: 34.18598, lng: -118.69345 },
      { lat: 34.18795, lng: -118.69030 },
      { lat: 34.18968, lng: -118.68621 },
      { lat: 34.19086, lng: -118.68149 },
      { lat: 34.19180, lng: -118.67598 },
      { lat: 34.19212, lng: -118.67094 },
    ],
  },
];

export interface StructureEdge {
  id: string;
  name: string;
  /** On-terrain label wording for this edge. */
  label: string;
  description: string;
  /** Stage index at which this developed edge first lies on the spread boundary. */
  activeFromStage: number;
  ring: LatLng[];
  /** The boundary-facing chain of the band (used for the dashed edge line). */
  edgeLine: LatLng[];
}

/**
 * Developed edges adjacent to the spread zone (not parcel-accurate): thin
 * bands just inside the footprint boundary where it meets neighborhoods.
 * These mark structure-adjacent terrain, not building damage.
 */
export const STRUCTURE_EDGES: StructureEdge[] = [
  {
    id: 'west-hills',
    name: 'West Hills edge',
    label: 'Structure-edge resistance',
    description: 'Residential boundary along Victory Blvd / Valley Circle.',
    activeFromStage: 1,
    ring: [
      { lat: 34.19121, lng: -118.66714 },
      { lat: 34.18988, lng: -118.66557 },
      { lat: 34.18803, lng: -118.66502 },
      { lat: 34.18603, lng: -118.66494 },
      { lat: 34.18403, lng: -118.66541 },
      { lat: 34.18204, lng: -118.66620 },
      { lat: 34.18245, lng: -118.66796 },
      { lat: 34.18427, lng: -118.66717 },
      { lat: 34.18610, lng: -118.66670 },
      { lat: 34.18793, lng: -118.66678 },
      { lat: 34.18962, lng: -118.66733 },
      { lat: 34.19084, lng: -118.66890 },
    ],
    edgeLine: [
      { lat: 34.19121, lng: -118.66714 },
      { lat: 34.18988, lng: -118.66557 },
      { lat: 34.18803, lng: -118.66502 },
      { lat: 34.18603, lng: -118.66494 },
      { lat: 34.18403, lng: -118.66541 },
      { lat: 34.18204, lng: -118.66620 },
    ],
  },
  {
    id: 'hidden-hills',
    name: 'Hidden Hills north edge',
    label: 'Neighborhood edge risk',
    description: 'Closest approach to the Hidden Hills community.',
    activeFromStage: 3,
    ring: [
      { lat: 34.17516, lng: -118.67658 },
      { lat: 34.17437, lng: -118.68005 },
      { lat: 34.17414, lng: -118.68368 },
      { lat: 34.17477, lng: -118.68700 },
      { lat: 34.17602, lng: -118.68987 },
      { lat: 34.17720, lng: -118.68934 },
      { lat: 34.17595, lng: -118.68670 },
      { lat: 34.17532, lng: -118.68366 },
      { lat: 34.17555, lng: -118.68033 },
      { lat: 34.17634, lng: -118.67715 },
    ],
    edgeLine: [
      { lat: 34.17516, lng: -118.67658 },
      { lat: 34.17437, lng: -118.68005 },
      { lat: 34.17414, lng: -118.68368 },
      { lat: 34.17477, lng: -118.68700 },
      { lat: 34.17602, lng: -118.68987 },
    ],
  },
];

export const IGNITION_POINT: LatLng = { lat: 34.185198, lng: -118.66991 };

/** Camera framing for the photorealistic 3D scene. */
export const SCENE_CAMERA = {
  /** Wide establishing view used before the fly-in. */
  initial: {
    center: { lat: 34.18295, lng: -118.67911, altitude: 300 },
    range: 17000,
    tilt: 38,
    heading: -30,
  },
  /** Main cinematic view: from the southeast, looking northwest along the burn axis. */
  main: {
    center: { lat: 34.18295, lng: -118.67911, altitude: 300 },
    range: 5200,
    tilt: 65,
    heading: -48,
  },
  flyInMillis: 4500,
} as const;
